### ISSUE TITLE
Feature request: custom area 

### ISSUE THREAD

**Issue by heiko1988** [bertreb/pimatic-deebot#1]
The command works I have test directly with the npm package:

vacbot.run(“CustomArea”, “start”, “1890.000000,-1661.000000,288.000000,-3069.000000”, “1”);

comma-separated list of exactly 4 position values for x1,y1,x2,y2 (e.g. -3975.000000,2280.000000,-1930.000000,4575.000000)
cleanings
1, 2

The Coordinates in a variable or directly in the rule. Cleaning is 1x or 2x the Custom area. 

How find the Coordinates
[https://github.com/mrbungle64/ecovacs-deebot.js/issues/18](https://github.com/mrbungle64/ecovacs-deebot.js/issues/18)

**Comment by bertreb** [comment]
I released version 0.0.22 with the clean area command.
Syntax:     deebot cleanarea [x1,y1,x2,y2]|$area-variable cleanings 1..2|$cleanings-variable

**Comment by heiko1988** [comment]
Hi,
tried different options. But unfortunately I have not yet managed to clean the area.

So he does not start cleaning, the normal things like room cleaning, fan speed. are OK

**Comment by bertreb** [comment]
Ok, what is the exact syntax you used testing it via the commandline? You already posted that.

**Comment by bertreb** [comment]
I change the internal custom area command in version 0.0.23. Please test it.

**Comment by heiko1988** [comment]
Yes now work perfect, and make a custom clean :)

> Ok, what is the exact syntax you used testing it via the commandline? You already posted that.
this is the exact syntax use in the commandline:

vacbot.run("CustomArea", "start", "-1875.000000,-1314.000000,613.000000,-3113.000000", "1");

**Comment by bertreb** [comment]
Thanks, i will close this request. You can open a new one if needed

**Comment by heiko1988** [comment]
Tanks :)

**Comment by bertreb** [comment]
Request implemented
