### ISSUE TITLE
Can pleas update to version 0.3.7 the library

### ISSUE THREAD

**Issue by heiko1988** [bertreb/pimatic-deebot#2]
Hi,

Can you please update ecovacs-deebot.js to the version to 0.3.7
A lot of bug fixes in mqtt and more

Regards :)

**Comment by bertreb** [comment]
I released version 0.0.24, based on ecovacs-deboot 0.3.7

**Comment by heiko1988** [comment]
Hi,

Can pleas update to the newst lib version.

Regards

**Comment by bertreb** [comment]
You can update to version 0.0.25. Thats supporting ecovacs-deebot version 0.4.3

**Comment by heiko1988** [comment]
Thanks :)
I check later out the new version.

**Comment by bertreb** [comment]
Version 0.26 is published with support of ecovacs-deebot 0.4.4 (support of 920)
