### ISSUE TITLE
Exceptions when running the Bot. 

### ISSUE THREAD

**Issue by scobby** [bertreb/pimatic-deebot#3]
I Have a Deebot 920 and after installation the Plugin and adding the bot. My pimatic instance is constantly restarting.

error [pimatic]: An uncaught exception occurred: TypeError: Cannot read property 'attributes' of null
    at EcovacsMQTT._message_to_dict (/home/pi/pimatic-app/node_modules/pimatic-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:292:18)
    at EcovacsMQTT._handle_message (/home/pi/pimatic-app/node_modules/pimatic-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:266:28)
    at MqttClient.EcovacsMQTT.client.on (/home/pi/pimatic-app/node_modules/pimatic-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:79:18)
    at MqttClient.emit (events.js:198:13)
    at MqttClient._handlePublish (/home/pi/pimatic-app/node_modules/pimatic-deebot/node_modules/ecovacs-deebot/node_modules/mqtt/lib/client.js:1162:12)
    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-deebot/node_modules/ecovacs-deebot/node_modules/mqtt/lib/client.js:351:12)
    at work (/home/pi/pimatic-app/node_modules/pimatic-deebot/node_modules/ecovacs-deebot/node_modules/mqtt/lib/client.js:283:12)
    at Writable.writable._write (/home/pi/pimatic-app/node_modules/pimatic-deebot/node_modules/ecovacs-deebot/node_modules/mqtt/lib/client.js:294:5)
    at doWrite (/home/pi/pimatic-app/node_modules/pimatic-deebot/node_modules/ecovacs-deebot/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/pi/pimatic-app/node_modules/pimatic-deebot/node_modules/ecovacs-deebot/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/home/pi/pimatic-app/node_modules/pimatic-deebot/node_modules/ecovacs-deebot/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (_stream_readable.js:709:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:64:24)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by bertreb** [comment]
I'm using the ecovacs-deebot.js library and the model 920 isn't on the list of tested/supported devices.  The error log looks like a mqtt xml parse problem but i cant really debug the problem. 
You could help to solve this if you could ask the maker of the lib  (https://github.com/mrbungle64/ecovacs-deebot.js) if model 920 is supported.
And if 920 should work i would  need access to your cleaner(account) for debugging and test. Thats the way is developed this plugin for another pimatic user.

**Comment by bertreb** [comment]
I updated the plugin to the newest version (0.4.3) of the ecovacs-deebot lib.
You could try to update first (pimatic-deebot 0.0.25)

**Comment by scobby** [comment]
thx for the fast support, i will give it a try.

**Comment by bertreb** [comment]
Ok, very good. Is the instruction from mrbungle64 something you can do?

**Comment by djmvt** [comment]
Didn't follow this but after installing this update the plugin doesn't work anymore. Going back to the previous release.

**Comment by bertreb** [comment]
Ok, any debug/log info? I could try testing it, if you would change the password back to the test one?

**Comment by djmvt** [comment]
canvas@2.6.1 install /home/pi/pimatic-app/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v64-linux-glibc-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@10.15.2 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:349:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "--fallback-to-build" "--module=/home/pi/pimatic-app/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/pi/pimatic-app/node_modules/canvas/build/Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /home/pi/pimatic-app/node_modules/canvas
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/home/pi/pimatic-app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/pimatic-app/node_modules/canvas/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/pimatic-app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.19.97-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/pimatic-app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/pimatic-app/node_modules/canvas
node-pre-gyp ERR! node -v v10.15.2
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/home/pi/pimatic-app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/pimatic-app/node_modules/canvas/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/pimatic-app/package.json'
npm WARN pimatic-app No description
npm WARN pimatic-app No repository field.
npm WARN pimatic-app No README data
npm WARN pimatic-app No license field.

npm ERR! code ELIFECYCLE

Something wrong with installing canvas. Going back to an older version doesn't work anymore, same error.

**Comment by bertreb** [comment]
How did you go back to older version and did you delete and reinstall already?

**Comment by mrbungle64** [comment]
@djmvt 
Please follow this instructions:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot#Installation

**Comment by bertreb** [comment]
@mrbungle64

Hi, if you use ecovacs-deebot in a different environment (like Pimatic) where is canvas used for?

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> Hi, if you use ecovacs-deebot in a different environment (like Pimatic) where is canvas used for?

Hi @bertreb 
It is used to create map functionality and to identify the spot area during cleaning.

**Comment by djmvt** [comment]
canvas kept annoying me when trying to reinstall for some reason, also with the instructions from @mrbungle64. Weird thing is: pimatic-deebot have been running absolutely fine since the first tests a few weeks ago, so this was unexpected. But after deleting both canvas and deebot again and rebooted the Pi it looks like everything got installed again as it was supposed to be installed. deebot is running again.

@bertreb tried to go back to an older version with npm install pimatic-deebot@0.0.24
But no longer nescessary, everything is working again. thanks.

**Comment by bertreb** [comment]
@mrbungle64  Thanks for explaining. It seems that this issue is solved.

**Comment by mrbungle64** [comment]
In the meantime we also updated both Readme files on GitHub

- https://github.com/mrbungle64/ecovacs-deebot.js/blob/master/README.md
- https://github.com/mrbungle64/ioBroker.ecovacs-deebot/blob/master/README.md

**Comment by heiko1988** [comment]
> @mrbungle64
> 
> Hi, if you use ecovacs-deebot in a different environment (like Pimatic) where is canvas used for?

I become the same error by installing the new pimatic debot plugin version, and I not use iobroker or other debot tools. I have this only in pimatic

**Comment by mrbungle64** [comment]
> > @mrbungle64
> > Hi, if you use ecovacs-deebot in a different environment (like Pimatic) where is canvas used for?
> 
> I become the same error by installing the new pimatic debot plugin version, and I not use iobroker or other debot tools. I have this only in pimatic

Hi @heiko1988 

have you already read and followed the mentioned instructions?
https://github.com/mrbungle64/ecovacs-deebot.js/blob/master/README.md

**Comment by bertreb** [comment]
@heiko1988 and you could try the steps in the last post of @djmvt.

**Comment by heiko1988** [comment]
Oh, sorry have this not read, after Instal canvas. The plugin work fine aging withe the ozmo debot 950

Thanks :)

**Comment by scobby** [comment]
the deebot 920 is now supported by fixing this issue:
https://github.com/mrbungle64/ecovacs-deebot.js/issues/25

think the libary needs an update?

**Comment by mrbungle64** [comment]
@bertreb 
I released version 0.4.4 on npm
https://www.npmjs.com/package/ecovacs-deebot#changelog

I recommend that you also include these installation instructions with your project:
https://www.npmjs.com/package/ecovacs-deebot#installation

**Comment by bertreb** [comment]
@mrbungle64 thanks. I will add the instructions and update the pimatic plugin

**Comment by scobby** [comment]
Works like a charm! thx!
