### ISSUE TITLE
Attributes error

### ISSUE THREAD

**Issue by djmvt** [bertreb/pimatic-deebot#4]
After the last update the attributes in the pimatic-deebot device are no longer visible when setting them to "none" (to filter out the attributes not needed).
When setting attributes to all (while the normally selected attributes, in my case clean report, chargestate and batteryinfo, are still active) all attributes are shown. So the added attributes stay visible.
![Screenshot_20200407_183807](https://user-images.githubusercontent.com/16620825/78697105-97aed600-7900-11ea-8d45-8fb4c40d7933.jpg)
![Screenshot_20200407_185109](https://user-images.githubusercontent.com/16620825/78697229-c5941a80-7900-11ea-92cc-df10d9aab035.jpg)

**Comment by bertreb** [comment]
There's no change in the deebot plugin except the new ecovacs-deebot lib (support of 920)
I assume you did all the restart and clear cache/browser things?

**Comment by djmvt** [comment]
Yes I did. Another strange thing: my deebot didn't work last night (normally it cleans at 4am) but started working this morning at 8.19am for some reason. Nothing in the log in the deebot app so that was kinda weird.

**Comment by bertreb** [comment]
I did a check, fix and released version 0.0.27.

**Comment by djmvt** [comment]
Yes! Fixed 👍
Still a lot of errors while installing canvas when updating the plugin but other than that it seems to work as expected now.

**Comment by bertreb** [comment]
Ok fine. Do you need to install canvas again after an update?

**Comment by djmvt** [comment]
No Canvas gets installed automatically again when updating pimatic-deebot. No issues with that now.
It just looks "ugly". When updating pimatic-deebot the log gets flooded with a lot of messages, all related to canvas. But it works, that's most important. Thanks!

**Comment by heiko1988** [comment]
Yes the flood of messages by update the plugin is heavy, after the update the plugin work normally.

**Comment by heiko1988** [comment]
Hi,

Ist not a problem with the plugin, is a question for pimatic. 

@djmvt how have you add robbie last run?
In the first pic the last row. 
Can pleas tell me, Regards :)
