### ISSUE TITLE
Pimatic gives an error on deebot r95mk2

### ISSUE THREAD

**Issue by djmvt** [bertreb/pimatic-deebot#5]
My deebot r95mk2 was broken so I had to get the main board replaced. Now I'm trying to reconnect the deebot with pimatic and although it gets recognised the device status is not updating. Also buttons and rules I had are no longer working. Ofcourse I changed all deebot related entries in the rules section to the "new" deebot device (new id).

Pimatic throws this error: getting devices TypeError: Cannot read property 'product' of undefined

Any ideas?

**Comment by bertreb** [comment]
Did you delete the old device and discovered the new one?

**Comment by djmvt** [comment]
Yes I did. And it gets discovered but keeps throwing me this error.

**Comment by bertreb** [comment]
And you used the latest version?

**Comment by djmvt** [comment]
Yes, installed the latest version yesterday.

**Comment by heiko1988** [comment]
I think ist not a problem with the debot plugin. I think is a pimatic problem.

I had the problem with another plugin.
After reinstall pimatic aging, work all fine. 

The deebot plugin work for me fine :)


What say the startup log. Wenn you pimatic directly start in the console?

**Comment by djmvt** [comment]
@heiko1988 did you reinstall the deebot plugin or pimatic?

**Comment by bertreb** [comment]
The error is coming from the ecovacs lib, i can't debug it because i can't reproduce it.
do you have another rpi/pimatic instance you can install deebot and try?

**Comment by djmvt** [comment]
No I don't. I can give you permission again to log in to the ecovacs account if that helps?

**Comment by bertreb** [comment]
Yes, i can try that. Use the pimatic chat for the temp pass

**Comment by bertreb** [comment]
The problem is found in the ecovacs-deebot release of 6 may ('added modelName and imageURL'). Not listed devices in the ecovacs-deebot lib cause an error after this release.
I issued a request to add the r95mk2 to solve the problem of the r95mk2. There's a patch available to solve this also (let me know if you need it)

**Comment by djmvt** [comment]
If it's easy to install the patch I would like to have that! Thanks Bert for this research!-------- Oorspronkelijk bericht --------Van: Bert <notifications@github.com>Datum: do 18 jun. 2020 08:02Aan: bertreb/pimatic-deebot <pimatic-deebot@noreply.github.com>Cc: djmvt <mvantrijffel@gmail.com>, Author <author@noreply.github.com>Onderwerp: Re: [bertreb/pimatic-deebot] Pimatic gives an error on deebot r95mk2 (#5)
The problem is found in the ecovacs-deebot release of 6 may ('added modelName and imageURL'). Not listed devices in the ecovacs-deebot lib cause an error after this release.
I issued a request to add the r95mk2 to solve the problem of the r95mk2. There's a patch available to solve this also (let me know if you need it)

**Comment by bertreb** [comment]
Version 0.0.30 is released, with a fix in the ecovac-deebot lib (0.4.16) to solve this problem.
