### ISSUE TITLE
Error getting devices, try to reconnect in 5 minutes Error: Cannot find module 'duplexify'

### ISSUE THREAD

**Issue by scobby** [bertreb/pimatic-deebot#7]
Deebot not working anymore, think its missing a npm dependency.
Using the current version 0.0.34

**Comment by bertreb** [comment]
This can be a problem with pimatic installing plugins.
The dependency and a lot of others are dependencies from libraries i use and they should be installed automatically.
You can add the missing dependencies manually via commandline in /home/pi/pimatic-app/node_modules/pimatic-deebot, npm install duplexify.
After installation restart pimatic.

**Comment by scobby** [comment]
hmmm i think this didnt work. After that command, all packages from pimatic are deleted. Had to reinstall pimatic completly. 
Can you add duplexify to the dependencies?

**Comment by bertreb** [comment]
Ok, that's bad. That should not have happend when you executed the command after going into the right deebot directory (cd /home/pi/pimatic-app/node_modules/pimatic-deebot) and checked that in the deebot directory the package.json is also present It should be).

So you also reinstalled deebot, is the problem still there?

**Comment by scobby** [comment]
Tried it again today, and yeah it fixed it! thx!
